#!/usr/bin/env python3

# GEP2 Super-Report Generator
# 2026
# This script is part of the GEP2 pipeline

# Aggregates results from multiple {asm_id}_report.md files (generated by
# make_gep2_report.py) into a single overview table across a GEP2 pipeline
# run (or just multiple .md-files created from multiple pipeline run's), with heatmap-style quality ratings based on EBP/VGP standards.

from __future__ import annotations

import argparse
import os
import re
import sys
import pandas as pd
from datetime import datetime, timezone
from typing import Any, Optional

__version__ = "0.1.0"

# -------------------------------------------------------------------------------
# TYPE ALIASES
# -------------------------------------------------------------------------------

AssemblyData = dict[str, Any]          # result of parse_assembly_report()
ThresholdSpec = dict[str, Any]         # one entry of THRESHOLDS
SuperTable = pd.DataFrame              # uses pandas-DataFrame

# -------------------------------------------------------------------------------
# THRESHOLDS / CONFIGURATION
# -------------------------------------------------------------------------------

THRESHOLDS: dict[str, ThresholdSpec] = {
    "contig_n50": {
        "source": "EBP Report v7 (2026) / VGP-Notation",
        "direction": "higher_better",
        "tiers": [(1_000_000, "PASS")],   # > 1 Mb (part of 6.C.Q40)
        "fallback": "FAIL",
    },
    "scaffold_n50": {
        "source": "EBP Report v7 (2026)",
        "direction": None,
        "tiers": None,
    },
    "gaps_per_gbp": {
        "source": "VGP-Paper",
        "direction": "lower_better",
        "tiers": [(200, "****"), (1000, "***-"), (10000, "**--")],
        "fallback": "*---",
    },
    "structural_errors": {
        "source": None,
        "direction": None,
        "tiers": None,
    },
    "false_duplications_pct": {
        # not applied directly - no clean value extractable from the
        # Markdown reports, using busco_duplicated_pct as a proxy instead
        "source": "EBP Report v7 (2026)",
        "direction": "lower_better",
        "tiers": [(5.0, "PASS")],
        "fallback": "FAIL",
    },
    "merqury_qv": {
        "source": "EBP Report v7 (2026) / VGP-Notation",
        "direction": "higher_better",
        "tiers": [(40.0, "PASS")],
        "fallback": "FAIL",
    },
    "kmer_completeness_pct": {
        "source": "EBP Report v7 (2026)",
        "direction": "higher_better",
        "tiers": [(90.0, "PASS")],
        "fallback": "FAIL",
    },
    "busco_single_pct": {
        "source": "EBP Report v7 (2026)",
        "direction": "higher_better",
        "tiers": [(90.0, "PASS")],
        "fallback": "FAIL",
    },
    "busco_duplicated_pct": {
        "source": "Pipeline-internal heuristic, conceptually supported by "
                   "Simao et al. 2015 ('should be rare'), no exact "
                   "literature value",
        "direction": "lower_better",
        "tiers": [(2.0, "****"), (5.0, "***-"), (7.0, "**--")],
        "fallback": "*---",
    },
    "chrom_seq_pct": {
        # not applied directly - not extractable from the Markdown reports,
        # using l90_haploid_proxy as a proxy instead
        "source": "EBP Report v7 (2026)",
        "direction": "higher_better",
        "tiers": [(90.0, "PASS")],
        "fallback": "FAIL",
    },
    "l90_haploid_proxy": {
        "source": "GEP2-internal, proxy for chrom_seq_pct",
        "direction": "lower_better",
        "tiers": lambda ctx: (
            [
                (ctx["haploid_number"], "****"),
                (ctx["haploid_number"] + 100, "***-"),
                (ctx["haploid_number"] + 1000, "**--"),
            ]
            if ctx.get("haploid_number") is not None
            else None
        ),
        "inclusive": True,  # "L90 <= n", not "L90 < n"
        "fallback": "*---",
    },
}


# -------------------------------------------------------------------------------
# MARKDOWN-REPORT-PARSING
# -------------------------------------------------------------------------------

def _clean_numeric(raw: str) -> Optional[float]:
    """
    Removes table formatting (thousand separators, % signs) and converts
    to float. Returns None for 'N/A' or empty cells.

    CAUTION: this results in data loss compared to the actual raw pipeline
    values, because format_number() in make_gep2_report.py has already
    rounded the values (e.g., values < 10 to 4 decimal places, >= 100 as
    integers with thousands separators).

    This is a deliberate trade-off to decouple the process from the
    pipeline run - see the "Limitations" chapter of the thesis.
    """
    
    raw = raw.strip()
    if (not raw) or raw.upper() in ("N/A", "NAN"):
        return None
    raw = raw.replace(",", "").replace("%", "").strip()
    try:
        return float(raw)
    except ValueError:
        return None
    
def _map_metric_label(label: str) -> Optional[str]:
    """
    Maps a metric label from the Markdown table (e.g., 'COMPL Sing. (e)' to our internal column name (e.g., 'eukaryota_single').
    
    Uses partial string matching instead of an exact dictionary, because the label varies depending on
    the pipeline configuration (COMPL vs. BUSCO, MERQ vs. MERQ.FK,
    (e) vs. (x) for the second lineage)—see the add_metric() calls in make_gep2_report.py:generate_report(). 
    
    Unknown/unnecessary labels (e.g., 'GC %', 'Scaffolds') are intentionally ignored (None).
    """
    
    label = re.sub(r"\s+", " ", label.strip())
    
    if label == "Total bp":
        return "total_bp"
    if label.startswith("Contig N50"):
        return "contig_n50"
    if label.startswith("Scaffold N50"):
        return "scaffold_n50"
    if label.startswith("Gaps/Gbp"):
        return "gaps_per_gbp"
    if label.startswith("Scaffold L90"):
        return "scaffold_l90"
    if label.startswith(("COMPL Sing.", "BUSCO Sing.")):
        return "eukaryota_single" if "(e)" in label else "other_single"
    if label.startswith(("COMPL Dupl.", "BUSCO Dupl.")):
        return "eukaryota_dupl" if "(e)" in label else "other_dupl"
    if label.startswith("INSP Str. Error"):
        return "structural_errors"
    if label.endswith("QV"):
        return "merqury_qv"
    if label.endswith("Compl.") and not label.startswith(("COMPL", "BUSCO")):
        return "merqury_completeness"
    
    return None

def parse_assembly_report(report_path: str) -> AssemblyData:
    """
    Parses a previously generated {asm_id}_report.md file (from make_gep2_report.py) and extracts raw data from it.
    """
    
    with open(report_path, encoding="utf-8") as f:
        content = f.read()
        
    result: AssemblyData = {
        "species": None, "taxon_id": None, "family": None, "asm_id": None,
        "haploid_number": None, "num_assemblies": 0, "completeness_tool": None, "kmer_tool": None,
        "metrics": {}
    }
    
    # --------------------
    header_match = re.search(r"^### (.+?) \(ID:\s*(.+?)\)\s*$", content, re.MULTILINE)
    if header_match:
        result["species"] = header_match.group(1).strip()
        taxon_id_raw = header_match.group(2).strip()
        result["taxon_id"] = None if taxon_id_raw == "not found" else taxon_id_raw

    # --------------------
    family_match = re.search(r"^##### (.+)$", content, re.MULTILINE)    
    if family_match:
        result["family"] = family_match.group(1).strip()
    
    # --------------------
    asm_id_match = re.search(r"^#### (.+)$", content, re.MULTILINE)
    if asm_id_match:
        result["asm_id"] = asm_id_match.group(1).strip()
    
    # --------------------
    # Haplotype count AND its source (e.g., “ancestor” vs. “direct”) -> the source is an important indicator of reliability
    # “ancestor”-derived values can be significantly off for groups with poor taxonomic coverage
    
    haploid_match = re.search(r"Haploid number is (\d+) \(([^,]+),", content)
    if haploid_match:
        result["haploid_number"] = int(haploid_match.group(1))
        result["haploid_source"] = haploid_match.group(2).strip()
    else:
        fallback_match = re.search(r"Haploid number is (\d+)", content)
        if fallback_match:
            result["haploid_number"] = int(fallback_match.group(1))
    
    # --------------------
    euka_lineage_match = re.search(r"^e = (.+?)<br>", content, re.MULTILINE)
    if euka_lineage_match:
        result["eukaryota_lineage"] = euka_lineage_match.group(1).strip()
 
    other_lineage_match = re.search(r"^x = (.+?)<br>", content, re.MULTILINE)
    if other_lineage_match:
        result["other_lineage"] = other_lineage_match.group(1).strip()
    
    # --------------------
    table_lines = [l for l in content.splitlines() if l.strip().startswith("|")]
    if table_lines:
        header_cells = [c.strip() for c in table_lines[0].strip().strip("|").split("|")]
        num_assemblies = 2 if "asm2 value" in header_cells else 1
        result["num_assemblies"] = num_assemblies
 
        for line in table_lines[2:]:  # skip header + separator row
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 3:
                continue
 
            normalized_label = re.sub(r"\s+", " ", cells[0].strip())
            internal_key = _map_metric_label(cells[0])
 
            # Tool detection independent of whether the label is mapped,
            # so it's also recognized when e.g. only "COMPL Frame." occurs
            if normalized_label.startswith(("COMPL", "BUSCO")):
                result["completeness_tool"] = "BUSCO" if normalized_label.startswith("BUSCO") else "compleasm"
            if normalized_label.startswith(("MERQ",)):
                result["kmer_tool"] = "MerquryFK" if normalized_label.startswith("MERQ.FK") else "Merqury"
 
            if internal_key is None:
                continue
 
            values = [_clean_numeric(cells[1])]
            if num_assemblies == 2 and len(cells) >= 4:
                values.append(_clean_numeric(cells[3]))
            result["metrics"][internal_key] = values
 
    return result
    
# -------------------------------------------------------------------------------
# AGGREGATION ACROSS ALL ASSEMBLIES
# -------------------------------------------------------------------------------

def build_super_table(all_reports: list[AssemblyData]) -> SuperTable:
    """
    The list of parsed reports is consolidated into ONE long table: one
    row per individual assembly file (e.g., asm1/asm2 for diploid assemblies).
    
    completeness_tool/kmer_tool are included as separate columns (per
    row, not uniformly across the pipeline—see the discussion on the new
    architecture:
    different reports may have used different tools).
    
    They are used in render_markdown_table() for the
    markers/legend and are removed from the visible table there.
    """
    
    rows: list[dict[str, Any]] = []
    
    for entry in all_reports:
        species: str = entry["species"]
        asm_id: str = entry["asm_id"]
        num_assemblies = entry["num_assemblies"]
        metrics = entry["metrics"]
        
        base_fields = {
            "species": species,
            "asm_id": asm_id,
            "taxon_id": entry.get("taxon_id"),
            "family": entry.get("family"),
            "haploid_number": entry.get("haploid_number"),
            "haploid_source": entry.get("haploid_source"),
            "completeness_tool": entry.get("completeness_tool"),
            "kmer_tool": entry.get("kmer_tool"),
            "eukaryota_lineage": entry.get("eukaryota_lineage"),
            "other_lineage": entry.get("other_lineage"),
        }
        
        if num_assemblies == 0:
            rows.append({**base_fields, "asm_file_nr": None})
            continue
        
        for i in range(num_assemblies):
            row: dict[str, Any] = {**base_fields, "asm_file_nr": i + 1}
            for metric_key, values in metrics.items():
                row[metric_key] = values[i] if i < len(values) else None
            rows.append(row)
                  
    return pd.DataFrame(rows)


# -------------------------------------------------------------------------------
# RATING
# -------------------------------------------------------------------------------

def rate_value(
    metric_name: str,
    value: Optional[float],
    **context: Any,
) -> str:
    """
    Maps a raw value to a rating classification based on the THRESHOLDS listed above.
    '····' consistently means “no rating available” -> both when a raw value is missing and when a threshold is missing or inapplicable
    (e.g., structural errors, or an L90 proxy without a haploid_number).
    """
    
    if value is None:
        return "····"
 
    spec = THRESHOLDS.get(metric_name)
    if spec is None:
        return "····"
 
    tiers = spec.get("tiers")
    if callable(tiers):
        tiers = tiers(context)
    if not tiers:
        return "····"
 
    direction = spec.get("direction")
    inclusive = spec.get("inclusive", False)
    for boundary, rating in tiers:
        if direction == "higher_better" and value > boundary:
            return rating
        if direction == "lower_better":
            if inclusive and value <= boundary:
                return rating
            if not inclusive and value < boundary:
                return rating
 
    return spec.get("fallback", "····")


def add_ratings(super_table: SuperTable) -> SuperTable:
    """
    Adds an additional '<column>_rating' column for each metric column that can currently be rated.
    l90_haploid_proxy is handled separately because it also requires haploid_number per row as context 
    (now available, since haploid_number is extracted directly from the report header)
    """
    METRIC_COLUMN_MAP: dict[str, str] = {
        "contig_n50": "contig_n50",
        "gaps_per_gbp": "gaps_per_gbp",
        "eukaryota_single": "busco_single_pct",
        "eukaryota_dupl": "busco_duplicated_pct",
        "other_single": "busco_single_pct",
        "other_dupl": "busco_duplicated_pct",
        "merqury_qv": "merqury_qv",
        "merqury_completeness": "kmer_completeness_pct"
    }
 
    df = super_table.copy()
    for column, metric_name in METRIC_COLUMN_MAP.items():
        if column not in df.columns:
            continue
        numeric_values = pd.to_numeric(df[column], errors="coerce")
        df[f"{column}_rating"] = [
            rate_value(metric_name, None if pd.isna(v) else float(v))
            for v in numeric_values
        ]
        
    if "scaffold_l90" in df.columns:
        ratings = []
        for _, row in df.iterrows():
            v = row.get("scaffold_l90")
            n = row.get("haploid_number")
            v = None if pd.isna(v) else float(v)
            n = None if pd.isna(n) else int(n)
            ratings.append(rate_value("l90_haploid_proxy", v, haploid_number=n))
        df["scaffold_l90_rating"] = ratings 
        
    return df


# -------------------------------------------------------------------------------
# RENDERING / OUTPUT
# -------------------------------------------------------------------------------

COLUMN_DISPLAY_NAMES: dict[str, str] = {
    "species": "Species",
    "asm_id": "Assembly ID",
    "taxon_id": "Taxon ID",
    "family": "Family",
    "haploid_number": "Haploid Number",
    "asm_file_nr": "Assembly File #",
    "total_bp": "Total bp",
    "contig_n50": "Contig N50",
    "scaffold_n50": "Scaffold N50",
    "gaps_per_gbp": "Gaps/Gbp",
    "scaffold_l90": "Scaffold L90",
    "structural_errors": "Structural Errors",
    "eukaryota_single": "Gene Compl. Single (%)",
    "eukaryota_dupl": "Gene Compl. Dupl. (%)",
    "other_single": "Gene Compl. Single, other lineage (%)",
    "other_dupl": "Gene Compl. Dupl., other lineage (%)",
    "merqury_qv": "k-mer QV",
    "merqury_completeness": "k-mer Completeness (%)",
}

# Columns that identify/describe an assembly rather than measure it - kept
# even if a column happens to be entirely empty for THIS set of reports,
# unlike e.g. "other_lineage" which is dropped from the table below if no
# report in this run used a second lineage.
PROTECTED_COLUMNS = {"species", "asm_id", "asm_file_nr"}

# Text-valued columns (not numbers) - used to fix alignment by COLUMN NAME
# instead of hardcoded position, so adding/removing/reordering columns can't
# silently misalign a column again (happened before with "Other Lineage").
TEXT_COLUMNS = ["Species", "Assembly ID", "Taxon ID", "Family", "Other Lineage"]

BP_SCALE_COLUMNS = ["total_bp", "contig_n50", "scaffold_n50"]

def _format_bp(value: Any, human_readable: bool) -> str:
    """
    Formats bp-scaled values for the table.
    - human_readable=True -> shortened unit e.g. "2.46 Mb"
    - None / NaN -> empty string instead of "nan" in the table.
    """
    if value is None or (isinstance(value, float)) and pd.isna(value):
        return ""
    
    value = float(value)
    
    if not human_readable:
        return f"{value:,.0f}"
    
    abs_value = abs(value)
    if abs_value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f} Gb"
    if abs_value >= 1_000_000:
        return f"{value / 1_000_000:.2f} Mb"
    if abs_value >= 1_000:
        return f"{value / 1_000:.2f} Kb"
    
    return f"{value:.0f} bp"    

PLAIN_NUMERIC_COLUMNS: dict[str, int] = {
    "gaps_per_gbp": 1,
    "scaffold_l90": 0,
    "structural_errors": 0,
}

def _format_plain_numeric(value: Any, decimals: int) -> str:
    """Formats a non-bp numeric value without scientific notation, at a
    fixed number of decimals. Empty string instead of "nan" for missing values."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    return f"{float(value):,.{decimals}f}"

# Tool-neutral column labels + markers instead of tool-specific names
# (e.g., “Gene Compl. Single (%)” instead of “BUSCO Single (%)”/“compleasm Single (%)”),
# because different rows may have been generated using different tools
# (see architecture decision). 
# The marker indicates for each row which tool was actually run.

COMPLETENESS_COLUMNS = ["eukaryota_single", "eukaryota_dupl", "other_single", "other_dupl"]
KMER_COLUMNS = ["merqury_qv", "merqury_completeness"]
 
COMPLETENESS_TOOL_MARKERS: dict[str, str] = {"BUSCO": "*", "compleasm": "**"}
KMER_TOOL_MARKERS: dict[str, str] = {"Merqury": "\u2020", "MerquryFK": "\u2021"}  # † ‡

def _format_marked_column(df: pd.DataFrame, column: str, tool_column: str,
    marker_map: dict[str, str], legend: dict[str, str], legend_text_fn) -> pd.Series:
    """
    Attaches a tool marker to every (non-missing) cell value in a column, based on the tool used in that ROW.
    Intended for DISPLAY purposes only (string result); the original numeric column in super_table remains unchanged.
    """
    def _fmt(row):
        value = row[column]
        if pd.isna(value):
            return ""
        tool = row.get(tool_column)
        marker = marker_map.get(tool, "")
        if marker:
            legend[marker] = legend_text_fn(tool)
        return f"{value:.2f}{marker}"
    return df.apply(_fmt, axis=1)

def _format_haploid_number(row: pd.Series) -> str:
    """
    Indicates the haploid number with a warning marker if GoaT-Source isn't 'direct'.
    """
    value = row.get("haploid_number")
    if value is None or pd.isna(value):
        return ""
    source = row.get("haploid_source")
    marker = "" if source == "direct" else "\u26A0"  # ⚠ 
    return f"{int(value)}{marker}"

def _prepare_display_table(
    super_table: SuperTable,
    human_readable_bp: bool = False
    ) -> tuple[pd.DataFrame, dict[str, str]]:
    """
    General preparing-logic for render_markdown_table() and rende_html_heatmap().
    - haploid-number-marker, bp-scaling, sci-notation, tool-marker for gene-completess and k-mer-analysis, lineage legend, renaming of columns
    
    - rating-columns are not removed yet:
        - render_markdown_table() shows them as text-columns
        - render_html_heatmap() uses them for color coding and removes them afterwards
        
    Returns tuple(prepared table, legend)
    """
    df = super_table.copy()
    legend: dict[str, str] = {}
    
    if "haploid_number" in df.columns:
        has_non_direct = (
            "haploid_source" in df.columns
            and df["haploid_source"].fillna("direct").ne("direct").any()
        )
        df["haploid_number"] = df.apply(_format_haploid_number, axis=1)
        if has_non_direct:
            legend["\u26A0"] = (
                "Haploid number not measured directly, but estimated by GoaT from an ancestral taxon"
            )
            
    # bp-scaled columns: fix scientific notation + optional Kb/Mb/Gb display
    for col in BP_SCALE_COLUMNS:
        if col in df.columns:
            df[col] = df[col].apply(lambda v: _format_bp(v, human_readable_bp))
 
    # other numeric columns: scientific-notation fix only, no units
    for col, decimals in PLAIN_NUMERIC_COLUMNS.items():
        if col in df.columns:
            df[col] = df[col].apply(lambda v, d=decimals: _format_plain_numeric(v, d))
 
    for col in COMPLETENESS_COLUMNS:
        if col in df.columns:
            df[col] = _format_marked_column(
                df, col, "completeness_tool", COMPLETENESS_TOOL_MARKERS, legend,
                lambda tool: f"Gene-Completeness done with {tool}"
            )
 
    for col in KMER_COLUMNS:
        if col in df.columns:
            df[col] = _format_marked_column(
                df, col, "kmer_tool", KMER_TOOL_MARKERS, legend,
                lambda tool: f"k-mer-Analysis done with {tool}"
            )
    
    if "eukaryota_lineage" in df.columns:
        euka_lineages = sorted(df["eukaryota_lineage"].dropna().unique().tolist())
        if len(euka_lineages) == 1:
            legend["e"] = f"Reference Lineage: {euka_lineages[0]}"
        elif len(euka_lineages) > 1:
            legend["e"] = f"Reference Lineage varies across reports: {', '.join(euka_lineages)}"       
    
    df["other_lineage"] = df["other_lineage"].fillna("") if "other_lineage" in df.columns else ""

    # Drop columns that carry zero information for THIS set of reports
    # (e.g. "other_lineage" when no report ran a second lineage) - avoids
    # visual noise from a column that's blank in every single row. Identifier
    # columns are protected even if empty by chance.
    for col in list(df.columns):
        if col in PROTECTED_COLUMNS:
            continue
        is_all_empty = df[col].apply(
            lambda v: v is None
            or (isinstance(v, float) and pd.isna(v))
            or (isinstance(v, str) and v.strip() == "")
        ).all()
        if is_all_empty:
            df = df.drop(columns=[col])

    df = df.drop(columns=["completeness_tool", "kmer_tool", "haploid_source", "eukaryota_lineage"],
                 errors="ignore")
    df = df.rename(columns={**COLUMN_DISPLAY_NAMES, "other_lineage": "Other Lineage"})
 
    return df, legend 


def render_markdown_table(
    super_table: SuperTable,
    human_readable_bp: bool = False,
) -> str:
    """
    Markdown table with tool-neutral column names and footnote markers
    per row (e.g., "86.82*"), instead of tool-specific column names or
    a generic header row (which could be incorrect in mixed reports).
    """

    df, legend = _prepare_display_table(super_table, human_readable_bp)

    lines = [
        "# GEP2 Super-Report",
        "",
        f"- **Assemblies in this report:** {super_table['asm_id'].nunique()}",
        ""
    ]

    lines.append(df.to_markdown(index=False))
    lines.append("")
    
    if legend:
        for marker, text in sorted(legend.items()):
            lines.append(f"'{marker}'   {text}  ")
        lines.append("")
        
    return "\n".join(lines)


RATING_COLORS: dict[str, str] = {
    "****": "#63be7b",
    "***-": "#b7dfa3",
    "**--": "#ffeb84",
    "*---": "#f8696b",
    "PASS": "#63be7b",
    "FAIL": "#f8696b",
    "····": "#f0f0f0",  # no rating -> neutral
}

VALUE_DISPLAY_TO_RATING_COLUMN: dict[str, str] = {
    "Contig N50": "contig_n50_rating",
    "Gaps/Gbp": "gaps_per_gbp_rating",
    "Scaffold L90": "scaffold_l90_rating",
    "Gene Compl. Single (%)": "eukaryota_single_rating",
    "Gene Compl. Dupl. (%)": "eukaryota_dupl_rating",
    "Gene Compl. Single, other lineage (%)": "other_single_rating",
    "Gene Compl. Dupl., other lineage (%)": "other_dupl_rating",
    "k-mer QV": "merqury_qv_rating",
    "k-mer Completeness (%)": "merqury_completeness_rating",
}

def render_html_heatmap(
    super_table: SuperTable,
    human_readable_bp: bool = False,
    source_reports: Optional[list[str]] = None,
) -> str:
    """
    Creates HTML-document with color-coded cells based on the "_rating"-columns.

    Uses pandas.Styler instead of building HTML manually.

    source_reports: optional list of the input {asm_id}_report.md paths used
    to build this super-report - shown in the footer for traceability/
    reproducibility (which is otherwise lost once results are aggregated).
    """
    df, legend = _prepare_display_table(super_table, human_readable_bp)

    # style-df has same form as original df, just filled with CSS background color per cell-entry and no coloring for empty cells
    style_df = pd.DataFrame("", index=df.index, columns=df.columns)
    for value_col, rating_col in VALUE_DISPLAY_TO_RATING_COLUMN.items():
        if value_col not in df.columns or rating_col not in df.columns:
            continue
        style_df[value_col] = df[rating_col].apply(
            lambda r: f"background-color: {RATING_COLORS.get(r, '')}"
        )

    # remove rating-columns
    rating_columns = [c for c in df.columns if c.endswith("_rating")]
    df       = df.drop(columns=rating_columns)
    style_df = style_df.drop(columns=rating_columns)

    styler = df.style.apply(lambda _: style_df, axis=None).hide(axis="index")
    text_cols_present = [c for c in TEXT_COLUMNS if c in df.columns]
    if text_cols_present:
        styler = styler.set_properties(subset=text_cols_present, **{"text-align": "left"})
    table_html = styler.to_html()

    # --- Report metadata (header info bar) ---
    n_species = int(super_table["species"].nunique()) if "species" in super_table.columns else 0
    n_assemblies = (
        int(super_table[["species", "asm_id"]].drop_duplicates().shape[0])
        if {"species", "asm_id"}.issubset(super_table.columns) else 0
    )
    n_files = len(super_table)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    meta_items = [
        ("Generated", generated_at),
        ("Species", str(n_species)),
        ("Assemblies", str(n_assemblies)),
        ("Assembly Files", str(n_files)),
    ]
    meta_html = "".join(
        f'<div class="meta-item"><span class="meta-label">{label}</span>'
        f'<span class="meta-value">{value}</span></div>'
        for label, value in meta_items
    )

    # --- Legend boxes (both moved below the table) ---
    rating_legend_items = "".join(
        f'<li><span class="swatch" style="background-color:{color}"></span> {label}</li>'
        for label, color in (
            ("Very good (****/ PASS)", RATING_COLORS["****"]),
            ("Good (***-)", RATING_COLORS["***-"]),
            ("Medium (**--)", RATING_COLORS["**--"]),
            ("Weak (*--- / FAIL)", RATING_COLORS["*---"]),
            ("No rating available (····)", RATING_COLORS["····"]),
        )
    )

    marker_legend_html = ""
    if legend:
        marker_legend_html = "".join(
            f"<li><code>{marker}</code><span>{text}</span></li>"
            for marker, text in sorted(legend.items())
        )

    legend_boxes = f"""
    <div class="legend-container">
      <div class="legend-box">
        <h3>Rating Colors</h3>
        <ul class="rating-legend">{rating_legend_items}</ul>
      </div>
      {f'<div class="legend-box"><h3>Markers &amp; Footnotes</h3><ul class="legend">{marker_legend_html}</ul></div>' if marker_legend_html else ''}
    </div>
    """

    # --- Footer (provenance / reproducibility) ---
    footer_html = f'<footer>Generated by GEP2 Super-Report v{__version__}'
    if source_reports:
        names = ", ".join(os.path.basename(p) for p in source_reports)
        footer_html += f" &middot; Aggregated from {len(source_reports)} report file(s): {names}"
    footer_html += "</footer>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>GEP2 Super-Report</title>
<style>
:root {{ --accent: #2c3e50; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 2em auto;
  max-width: 1500px;
  padding: 0 1.5em;
  color: #222;
  line-height: 1.45;
}}
h1 {{
  margin-bottom: 0.15em;
  font-size: 1.9em;
  border-bottom: 3px solid var(--accent);
  padding-bottom: 0.35em;
}}
.subtitle {{ color: #666; margin-top: 0.2em; margin-bottom: 1.3em; font-size: 0.95em; }}
.report-meta {{
  display: flex; flex-wrap: wrap;
  background: #f4f6f8; border: 1px solid #e0e0e0; border-radius: 6px;
  padding: 0.7em 0; margin-bottom: 1.6em;
}}
.meta-item {{ padding: 0 1.6em; border-right: 1px solid #d8d8d8; }}
.meta-item:last-child {{ border-right: none; }}
.meta-item:first-child {{ padding-left: 1.6em; }}
.meta-label {{ display: block; font-size: 0.72em; text-transform: uppercase; letter-spacing: 0.05em; color: #888; }}
.meta-value {{ display: block; font-size: 1.15em; font-weight: 600; color: var(--accent); }}
.table-wrap {{ overflow-x: auto; border: 1px solid #ddd; border-radius: 6px; }}
table {{ border-collapse: collapse; width: 100%; font-size: 0.9em; }}
th, td {{ border: 1px solid #e6e6e6; padding: 7px 11px; text-align: right; white-space: nowrap; }}
th {{ background-color: var(--accent); color: white; position: sticky; top: 0; font-weight: 600; }}
tbody tr:nth-child(even) td {{ background-color: #f7f8fa; }}
tr:hover td {{ filter: brightness(0.95); }}
.legend-container {{ display: flex; gap: 1.4em; flex-wrap: wrap; margin-top: 1.8em; }}
.legend-box {{
  background: #fafafa; border: 1px solid #e0e0e0; border-radius: 6px;
  padding: 1em 1.4em; flex: 1; min-width: 280px;
}}
.legend-box h3 {{
  margin: 0 0 0.7em 0; font-size: 0.9em; text-transform: uppercase; letter-spacing: 0.05em;
  color: #555; border-bottom: 1px solid #ddd; padding-bottom: 0.45em;
}}
ul.rating-legend, ul.legend {{ list-style: none; padding-left: 0; margin: 0; }}
ul.rating-legend li, ul.legend li {{ display: flex; align-items: center; margin-bottom: 0.55em; font-size: 0.88em; }}
ul.legend code {{
  background: #eaeaea; padding: 4px 9px; border-radius: 4px; font-size: 1.05em;
  margin-right: 0.8em; min-width: 1.3em; text-align: center; display: inline-block;
}}
.swatch {{ display: inline-block; width: 14px; height: 14px; border: 1px solid #999; border-radius: 2px; margin-right: 0.7em; flex-shrink: 0; }}
footer {{ margin-top: 2.2em; padding-top: 1em; border-top: 1px solid #e6e6e6; font-size: 0.78em; color: #999; }}
@media print {{
  th {{ background-color: #eee !important; color: #000 !important; position: static; }}
  .table-wrap {{ overflow-x: visible; }}
}}
</style>
</head>
<body>
<h1>GEP2 Super-Report</h1>
<p class="subtitle">Aggregated genome assembly quality overview across multiple GEP2 pipeline reports</p>
<div class="report-meta">{meta_html}</div>
<div class="table-wrap">
{table_html}
</div>
{legend_boxes}
{footer_html}
</body>
</html>
"""

# -------------------------------------------------------------------------------
# CLI ENTRY POINT
# -------------------------------------------------------------------------------

def main() -> None:
    # ---------------------------------------------------------------
    # ------------------------ CLI-Section: -------------------------
    parser = argparse.ArgumentParser(
        description="Creates a 'super-report' across multiple {asm_id}_report.md-files created by the 'make_gep2_report.py'-script."
    )
    parser.add_argument(
        "--reports", required=True, nargs="+",
        help="paths to {asm_id}_report.md files"
    )
    parser.add_argument(
        "--output", required=True,
        help="output name of the super-report."
    )
    parser.add_argument(
        "--format", choices=["markdown", "html"], default="markdown",
        help="format of output file."
    )
    parser.add_argument(
        "--human-readable", action="store_true",
        help="shows bp-values as Kb/Mb/Gb instead of raw values."
    )
    
    args: argparse.Namespace = parser.parse_args()
    
    missing = [p for p in args.reports if not os.path.exists(p)]
    if missing:
        print(f"Error: report file(s) not found: {missing}", file=sys.stderr)
        sys.exit(1)
    # ---------------------------------------------------------------
    # ------------------ Aggregating of Results: --------------------

    all_data: list[AssemblyData] = [parse_assembly_report(p) for p in args.reports]
 
    print("\nImported Reports:")
    for data in all_data:
        print(f"  {data['species']} / {data['asm_id']} (Completeness: {data['completeness_tool']}, k-mer: {data['kmer_tool']})")    

    super_table: SuperTable = build_super_table(all_data)
    super_table = add_ratings(super_table)
 
    print("")
    print(super_table)
 
    # ---------------------------------------------------------------
    # ------------------------- Output: -----------------------------
 
    output_text: str
    if args.format == "markdown":
        output_text = render_markdown_table(super_table, human_readable_bp=args.human_readable)
    else:
        output_text = render_html_heatmap(
            super_table, human_readable_bp=args.human_readable, source_reports=args.reports
        )
 
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(output_text)
 
    print(f"\n'super-report' written to: {args.output}")


if __name__ == "__main__":
    main()